### PR TITLE
Add schema for Application Registry

### PR DESCRIPTION
**Pull request by mfrinnstrom**
This schema details what properties we will store for each application to start with.

### CODE REVIEW

**Review by JensESecuritas — COMMENTED** [review]
Is this still up to date after our meeting last week?

**Comment by mfrinnstrom** [comment]
I believe it should be. I edited it while we were talking.

**Review by JensESecuritas — APPROVED** [review]
LGTM

**Review by wilhelm-ohman — APPROVED** [review]
LGTM

**Pull request merged**
